# -*- coding: utf-8 -*-
"""qpsk_demod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyQyPjUGW0duYbME2RG9rixtoJf2Y70Y

## Librerías
"""

import re
import os
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm.auto import tqdm
from google.colab import files

"""## Constantes y funciones

### Constantes globales
"""

QPSK_CONSTELLATION = np.array([
    0.707 + 0.707j,   # 00
   -0.707 + 0.707j,   # 01
   -0.707 - 0.707j,   # 10
    0.707 - 0.707j    # 11
])

ASK4_CONSTELLATION = np.array([
   -3,   # 00
   -1,   # 01
    1,   # 10
    3    # 11
])

# DISTANCES = [0, 2, 20, 40]

"""### Manipulación de señales y bits"""

def sync_signals(tx, rx):
    """
    Sincroniza correlacionando componentes I y Q de forma independiente.
    """
    eps = 1e-9

    # Normalización
    def normalize_signal(s):
        # Separamos componentes para normalizar desvíos de DC y escala de forma independiente
        components = [s.real, s.imag]
        norm_comp = [(c - np.mean(c)) / (np.std(c) + eps) for c in components]
        return norm_comp

    tx_i, tx_q = normalize_signal(tx)
    rx_i, rx_q = normalize_signal(rx)

    # Correlaciones cruzadas (II y QQ)
    corr_ii = np.correlate(rx_i, tx_i, mode="full")
    corr_qq = np.correlate(rx_q, tx_q, mode="full")

    # Suma y detección de retardo (delay)
    total_corr = corr_ii + corr_qq
    delay = np.argmax(total_corr) - (len(tx) - 1)

    # Recorte y alineación
    if delay < 0:
        # El receptor empezó después que el transmisor (o hay pérdida inicial)
        rx_sync = rx[: len(tx) + delay]
        tx_sync = tx[-delay : -delay + len(rx_sync)]
    else:
        # El receptor tiene un retraso positivo
        rx_sync = rx[delay : delay + len(tx)]
        tx_sync = tx[: len(rx_sync)]

    return tx_sync, rx_sync, delay, corr_ii, corr_qq

def plot_constellation(signal, metadata=None, title="Constellation Diagram"):
    """
    Grafica el diagrama de constelación.
    """
    plt.figure(figsize=(6, 7))
    plt.scatter(signal.real, signal.imag, s=1, alpha=0.5, color='royalblue')

    # Estética y ejes
    plt.axhline(0, color='black', linewidth=0.8, alpha=0.5)
    plt.axvline(0, color='black', linewidth=0.8, alpha=0.5)
    plt.grid(True, linestyle=':', alpha=0.6)

    # Formateo de metadata enfocado en SNR y OSNR
    if metadata:
        # Extraemos valores con un fallback de "N/A" si no existen
        snr = metadata.get('snr_db', 'N/A')
        osnr = metadata.get('osnr_db', 'N/A')
        pwr = metadata.get('launch_power_dbm', 'N/A')
        dist = metadata.get('distance_km', 'N/A')

        full_title = f"{title}\nSNR: {snr} dB | OSNR: {osnr} dB"
        sub_info = f"Power: {pwr} dBm | Distance: {dist} km"

        plt.suptitle(full_title, fontsize=12, fontweight='bold')
        plt.title(sub_info, fontsize=9, color='dimgray')
    else:
        plt.title(title)

    # Ajuste dinámico de límites para evitar distorsión
    limit = np.max(np.abs(signal)) * 1.2 if len(signal) > 0 else 1
    plt.xlim(-limit, limit)
    plt.ylim(-limit, limit)

    plt.xlabel("In-Phase (I)")
    plt.ylabel("Quadrature (Q)")
    plt.gca().set_aspect('equal')
    plt.tight_layout()
    plt.show()

def plot_correlation_results(corr_ii, corr_qq, lags, metadata=None, title="Correlation Analysis"):
    """
    Graficar correlaciones real y compleja.
    """
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6), sharex=True)

    # Metadata en el encabezado
    if metadata:
        snr = metadata.get('snr_db', 'N/A')
        osnr = metadata.get('osnr_db', 'N/A')
        fig.suptitle(f"{title}\nSNR: {snr} dB | OSNR: {osnr} dB", fontsize=12, fontweight='bold')

    # Configuración de ejes para I y Q
    plots = [
        (ax1, corr_ii, "I", "dodgerblue"),
        (ax2, corr_qq, "Q", "limegreen")
    ]

    for ax, data, label, color in plots:
        peak_idx = np.argmax(np.abs(data))
        delay = lags[peak_idx]

        ax.plot(lags, data, label=label, color=color, lw=1.2)
        ax.axvline(delay, color='red', ls='--', alpha=0.7, label=f"Peak: {delay}")
        ax.legend(loc='upper right', fontsize='small')
        ax.grid(True, alpha=0.3)

    plt.xlabel("Lag (samples)")
    plt.tight_layout()
    plt.show()

"""### Modulación y demodulación"""

def modulate(bits, constellation):
    """
    Modula bits a símbolos.
    """
    # Determinar bits por símbolo (k) basado en el tamaño de la constelación
    M = len(constellation)
    k = int(np.log2(M))

    # Padding: Asegurar que el flujo de bits sea múltiplo de k
    remainder = len(bits) % k
    if remainder != 0:
        bits = np.append(bits, np.zeros(k - remainder, dtype=int))

    # Agrupar bits y convertir a índices decimales
    # Reshape para tener filas de tamaño 'k'
    reshaped_bits = bits.reshape(-1, k)

    # Convertir cada fila de bits a un índice decimal (MSB primero)
    # [1, 0] -> 1*2^1 + 0*2^0 = 2
    powers = 2**np.arange(k-1, -1, -1)
    indexes = np.dot(reshaped_bits, powers)

    return constellation[indexes]

def demodulate(signal, constellation):
    """
    Demodula buscando el símbolo más cercano (Hard Decision).
    """
    M = len(constellation)
    k = int(np.log2(M))

    # 1. Encontrar el índice del símbolo más cercano en la constelación para cada punto
    distances = np.abs(signal[:, None] - constellation[None, :])
    sym_indices = np.argmin(distances, axis=1)

    # 2. Convertir índices decimales de vuelta a bits
    # Creamos una matriz donde cada fila es la representación binaria del índice
    # Ejemplo para k=2: 0->[0,0], 1->[0,1], 2->[1,0], 3->[1,1]
    bit_map = np.array([[int(b) for b in format(i, f'0{k}b')] for i in range(M)])

    # Extraemos los bits correspondientes a los índices detectados
    bits = bit_map[sym_indices].flatten()

    return bits

"""### Utilidades"""

def extract_value(pattern, text, conversion_func=float):
    """
    Función interna genérica para buscar un patrón en el texto.
    """
    # Buscar el patrón ignorando mayúsculas/minúsculas
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        value_str = match.group(1)
        # Reemplazar la 'p' por punto decimal para poder convertir a float
        if 'p' in value_str:
            value_str = value_str.replace('p', '.')
        return conversion_func(value_str)
    return None

def get_launch_power(filename):
    # Busca potencia en dBm (soporta negativos, ej: -3dBm o 0p5dBm)
    return extract_value(r"([-+]?\d+(?:p\d+)?)dbm", filename)

def get_distance(filename):
    return extract_value(r"(\d+(?:p\d+)?)km", filename)

def get_osnr(filename):
    return extract_value(r"osnr(\d+p\d+)db", filename)

def get_snr(filename):
    return extract_value(r"(?<!o)snr(\d+p\d+)db", filename)

def get_carrier_freq(filename):
    return extract_value(r"(\d+)mhz", filename, int)

def get_bitrate(filename):
    return extract_value(r"(\d+)mbps", filename, int)

def parse_filename_metadata(filename):
    """
    Extrae todos los parámetros y los devuelve en un diccionario.
    """
    metadata = {
        "launch_power_dbm": get_launch_power(filename),
        "distance_km":      get_distance(filename),
        "osnr_db":          get_osnr(filename),
        "snr_db":           get_snr(filename),
        "freq_mhz":         get_carrier_freq(filename),
        "bitrate_mbps":     get_bitrate(filename)
    }
    return metadata

def load_results(output_filename):
    # Intentar cargar la base de datos existente
    if os.path.exists(output_filename):
        results_df = pd.read_csv(output_filename)
        # Usamos un set de los nombres de archivos ya procesados para una búsqueda rápida
        processed_files = set(results_df['filename'].unique())
        # Convertimos el dataframe a lista de diccionarios para seguir añadiendo
        results_list = results_df.to_dict('records')
        print(f"✅ Base de datos cargada: {len(results_list)} registros previos.")
    else:
        results_list = []
        processed_files = set()
        print("❌ No hay resultados previos. Se creará una nueva base de datos.")
    return results_list, processed_files

"""## Proceso principal"""

def main_pipeline(rx_paths, processed_files, results_list, output_filename):
    # Iniciamos el cronómetro global
    start_time = time.time()

    for path in rx_paths:
        if not os.path.exists(path):
            print(f"⚠️ Saltando {path}: archivo no encontrado.")
            continue

        current_npz = np.load(path, allow_pickle=True)
        all_files = current_npz.files

        # Filtrar archivos que ya procesamos para que la barra de progreso sea real
        files_to_process = [f for f in all_files if f not in processed_files]
        skipped = len(all_files) - len(files_to_process)

        print(f"\n📂 NPZ: {path}")
        if skipped > 0:
            print(f"⏩ Saltando {skipped} archivos ya procesados...")

        # Barra de progreso para los archivos de este NPZ
        pbar = tqdm(files_to_process, desc=f"Procesando {path}", unit="file")

        for name in pbar:
            metadata = parse_filename_metadata(name.lower())
            rx_signal = current_npz[name]
            rotation_results = []

            # Actualizamos el texto de la barra con el OSNR actual (opcional)
            pbar.set_postfix(OSNR=metadata.get('osnr_db', '?'))

            for rot in [1, 1j, -1, -1j]:
                rx_rotated = rx_signal * rot

                # Sincronización y alineación
                tx_s, rx_s, delay, _, _ = sync_signals(tx_ref, rx_rotated)

                # Demodulación y cálculo de BER
                b_ref = demodulate(tx_s, QPSK_CONSTELLATION)
                b_rx  = demodulate(rx_s, QPSK_CONSTELLATION)

                n = min(len(b_ref), len(b_rx))
                if n == 0: continue

                ber = np.mean(b_ref[:n] != b_rx[:n])
                rotation_results.append({'ber': ber, 'delay': delay})

            if rotation_results:
                best_case = min(rotation_results, key=lambda x: x['ber'])
                metadata.update({
                    'filename': name,
                    'ber': best_case['ber'],
                    'detected_delay': best_case['delay'],
                    'npz_source': path
                })
                results_list.append(metadata)
                processed_files.add(name)

        # Guardado intermedio por cada NPZ terminado
        pd.DataFrame(results_list).to_csv(output_filename, index=False)
        print(f"✅ Progreso guardado. Total en BD: {len(results_list)}")
        files.download(output_filename)

    total_duration = time.time() - start_time
    print(f"\n✨ Pipeline finalizado en {total_duration:.2f} segundos.")

"""### Cargar datos"""

# Bits transmitidos (TX)
!gdown 1RXSmwwvAFrpuyjo6c7dU_lzNQmnJ80d5

# DFB (usando pasos de 1 dB)
# 0 km
# !gdown 1ERpfPPJqVCY3gV9Vxo4svllCwcyrIjzX
# # 2 km
# !gdown 1QRH4PaurMJRMW2gApy397tgAaNtPr1mA
# # 20 km
# !gdown 1wG_3o6nLCNEbYS0vhqqAYwu5cWXX7DHu
# # 40 km
# !gdown 1eOyne5EZ_WBe0zEzV1iYwHGWm7_qZM9r

# DFB (usando pasos de 0.4 dB)
# 0 km
!gdown 1rhLsooKt0OV0lrZVP1Tv2R3XzUR28Pa7
# 2 km
!gdown 1D2BV7jwCBB-Q5ngGfRHyGz87j68BXqBI
# 20 km
!gdown 1JSDd5HQYzCRjtUSnkKGZ10jrZi9aGpK7
# 40 km
!gdown 19rMA29ybHCWq4aYP1kteFCLPbA3NnxN5

# USPL (usando pasos de 1 dB)
# 0 km
!gdown 1Z9zuD-_BBi3R3kbk7paI15zlBOBQJkPG
# 20 km
!gdown 1zbjHAsjdIR_ZF05XvrPxVN3hG5I5ie4D

# Resultados
# DFB (usando pasos de 1 dB)
!gdown 19JF1TEHVNC4lDzKaHGdE6ki5wGvYF8aC
# DFB (usando pasos de 0.4 dB)
!gdown 19B_Y1dTr2U4_wrj9rUmiOZJopkWTBR7r
# USPL
!gdown 1KxWEcLxSasC5oK2UcHISLPjfEjdaPPdC

# Ruta al archivo de bits
TX_PATH = "tx.txt"

with open(TX_PATH, "r") as f:
    bitstring1 = f.read().strip()

print("Cantidad de bits:", len(bitstring1))
print("Primeros 50 bits:", bitstring1[:50])

bits_tx = np.array([int(b) for b in bitstring1], dtype=np.uint8)

# Referencia de transmisión
tx_ref = modulate(bits_tx, QPSK_CONSTELLATION)

"""## DFB"""

# WARN: Usamos datos antiguos porque los nuevos tardan demasiado en procesar
POWER = "0"
FREQ = "650"
#DATA_RATE = "2"
DATA_RATE = "1p88"
LASER_TYPE = "dfb"
DISTANCES = [0, 2, 20, 40]

#rx_paths_dfb = [f"rof_{POWER}dBm_{d}km_{FREQ}mhz_{DATA_RATE}mbps.npz" for d in DISTANCES]
rx_paths_dfb = [f"rof_{LASER_TYPE}_{POWER}dBm_{d}km_{FREQ}mhz_{DATA_RATE}mbps.npz" for d in DISTANCES]

data0, data2, data20, data40 = 0, 0, 0, 0
data_dfb = [data0, data2, data20, data40]

for datum, path in zip(data_dfb, rx_paths_dfb):
  datum = np.load(path, allow_pickle=True)
  print(f"📂 Datos de {path} cargados con {len(datum)} archivos")

"""### Evaluar"""

#output_filename_dfb = f"results_qpsk_{LASER_TYPE}.csv"
output_filename_dfb = f"results_qpsk_{LASER_TYPE}_extended.csv"
results_list_dfb, processed_files_dfb = load_results(output_filename_dfb)

main_pipeline(rx_paths_dfb, processed_files_dfb, results_list_dfb, output_filename_dfb)

"""## USPL"""

POWER = "-3"
FREQ = "650"
DATA_RATE = "1p88"
LASER_TYPE = "uspl"
DISTANCES = [0, 20]
rx_paths_uspl = [f"rof_{LASER_TYPE}_{POWER}dBm_{d}km_{FREQ}mhz_{DATA_RATE}mbps.npz" for d in DISTANCES]

data0, data20 = 0, 0
data_uspl = [data0, data20]

for datum, path in zip(data_uspl, rx_paths_uspl):
  datum = np.load(path, allow_pickle=True)
  print(f"📂 Datos de {path} cargados con {len(datum)} archivos")

"""### Evaluar"""

output_filename_uspl = f"results_qpsk_{LASER_TYPE}.csv"
results_list_uspl, processed_files_uspl = load_results(output_filename_uspl)

main_pipeline(rx_paths_uspl, processed_files_uspl, results_list_uspl, output_filename_uspl)

"""# TODO: MOVE TO ANOTHER NOTEBOOK

# Código fundador
"""

from collections import defaultdict

ber_osnr = defaultdict(list)

tx_ref = bits_to_qpsk(bits_tx)

for name in datos.files:

    osnr = extraer_osnr(name)
    if osnr is None:
        continue

    data = datos[name]
    resultados = []

    # ===== TU BLOQUE FUNCIONAL (SIN CAMBIOS) =====
    for k, rot in enumerate([1, 1j, -1, -1j]):
        rx_rot = data * rot
        tx_s, rx_s, _, corr_i, corr_q = sync_by_components(tx_ref, rx_rot)

        b_ref = demodular_qpsk(tx_s)
        b_rx  = demodular_qpsk(rx_s)

        n = min(len(b_ref), len(b_rx))
        # HOLA HANNA, ACÁ TAMBIÉN SE ESTÁ RECORTANDO, PERO SI ARREGLAS LA DE
        # ARRIBA ESTA YA NO HACE DAÑO Y LA PUEDES DEJAR ;D
        ber = np.mean(b_ref[:n] != b_rx[:n])

        resultados.append({'ber': ber})
    # ============================================

    mejor = min(resultados, key=lambda x: x['ber'])
    ber_osnr[osnr].append(mejor['ber'])

osnr_vals = sorted(ber_osnr.keys())
ber_mean = [np.mean(ber_osnr[o]) for o in osnr_vals]

plt.figure(figsize=(7,5))
plt.semilogy(osnr_vals, ber_mean, 'o-')
plt.grid(True, which='both')
plt.xlabel("OSNR (dB)")
plt.ylabel("BER")
plt.title("BER vs OSNR (QPSK)")
plt.show()

"""## BER vs SNR"""

from collections import defaultdict
import matplotlib.pyplot as plt

ber_snr = defaultdict(list)

tx_ref = bits_to_qpsk(bits_tx)

for name in datos.files:

    snr = extraer_snr(name)
    if snr is None:
        continue

    data = datos[name]
    resultados = []

    # ===== TU BLOQUE FUNCIONAL (SIN CAMBIOS) =====
    for k, rot in enumerate([1, 1j, -1, -1j]):

        rx_rot = data * rot
        tx_s, rx_s, _, _, _ = sync_by_components(tx_ref, rx_rot)

        b_ref = demodular_qpsk(tx_s)
        b_rx  = demodular_qpsk(rx_s)

        n = min(len(b_ref), len(b_rx))
        ber = np.mean(b_ref[:n] != b_rx[:n])

        resultados.append({'ber': ber})
    # ============================================

    mejor = min(resultados, key=lambda x: x['ber'])
    ber_snr[snr].append(mejor['ber'])

snr_vals = sorted(ber_snr.keys())
ber_mean = [np.mean(ber_snr[s]) for s in snr_vals]

plt.figure(figsize=(7,5))
plt.semilogy(snr_vals, ber_mean, 'o-')
plt.grid(True, which='both')
plt.xlabel("SNR (dB)")
plt.ylabel("BER")
plt.title("BER vs SNR (QPSK)")
plt.show()

snr_vals = np.array(sorted(ber_snr.keys()))
ber_vals = np.array([np.mean(ber_snr[k]) for k in snr_vals])

ber_smooth = moving_average(ber_vals, window=10)

plt.figure(figsize=(7,5))

plt.semilogy(snr_vals, ber_vals, 'o-', alpha=0.4, label="BER original")
plt.semilogy(snr_vals, ber_smooth, '-r', linewidth=2, label="BER suavizada")

plt.grid(True, which='both')
plt.xlabel("SNR / SMR (dB)")
plt.ylabel("BER")
plt.title("BER vs SNR (Media móvil)")
plt.legend()
plt.show()

#BER vs OSNR para 2 km

ber_osnr = defaultdict(list)

tx_ref = bits_to_qpsk(bits_tx1)

for name in datos1.files:

    osnr = extraer_osnr(name)
    if osnr is None:
        continue

    data = datos1[name]
    resultados = []

    # ===== TU BLOQUE FUNCIONAL (SIN CAMBIOS) =====
    for k, rot in enumerate([1, 1j, -1, -1j]):
        rx_rot = data * rot
        tx_s, rx_s, _, corr_i, corr_q = sync_by_components(tx_ref, rx_rot)

        b_ref = demodular_qpsk(tx_s)
        b_rx  = demodular_qpsk(rx_s)

        n = min(len(b_ref), len(b_rx))
        # HOLA HANNA, ACÁ TAMBIÉN SE ESTÁ RECORTANDO, PERO SI ARREGLAS LA DE
        # ARRIBA ESTA YA NO HACE DAÑO Y LA PUEDES DEJAR ;D
        ber = np.mean(b_ref[:n] != b_rx[:n])

        resultados.append({'ber': ber})
    # ============================================

    mejor = min(resultados, key=lambda x: x['ber'])
    ber_osnr[osnr].append(mejor['ber'])

"""## Depuración"""

#versión corregida de la función para tratar con los archivos de 2km:
def sync_by_components1(tx_ideal, rx_long):
    """
    Sincroniza correlacionando I y Q de forma independiente y sumando sus contribuciones.
    """
    eps = 1e-9  # <-- EPSILON para evitar colapso numérico

    # 1. Normalización ROBUSTA
    tx_i = (tx_ideal.real - np.mean(tx_ideal.real)) / (np.std(tx_ideal.real) + eps)
    tx_q = (tx_ideal.imag - np.mean(tx_ideal.imag)) / (np.std(tx_ideal.imag) + eps)

    rx_i = (rx_long.real - np.mean(rx_long.real)) / (np.std(rx_long.real) + eps)
    rx_q = (rx_long.imag - np.mean(rx_long.imag)) / (np.std(rx_long.imag) + eps)

    # 2. Correlaciones cruzadas independientes
    corr_ii = np.correlate(rx_i, tx_i, mode="full")
    corr_qq = np.correlate(rx_q, tx_q, mode="full")

    # 3. Suma de correlaciones
    total_corr = corr_ii + corr_qq

    lags = np.arange(-len(tx_ideal) + 1, len(rx_long))
    delay = lags[np.argmax(total_corr)]

    # 4. Recorte (igual que antes)
    if delay < 0:
        rx_sync = rx_long[0 : len(tx_ideal) + delay]
        tx_sync = tx_ideal[-delay : -delay + len(rx_sync)]
    else:
        rx_sync = rx_long[delay : delay + len(tx_ideal)]
        tx_sync = tx_ideal[:len(rx_sync)]

    return tx_sync, rx_sync, delay, corr_ii, corr_qq

name = "rof_0dBm_0km_osnrXdB_650mhz_1mbps_snrXdB.bin"
data = np.fromfile(name, dtype=np.complex64)
resultados = []
tx_ref = bits_to_qpsk(bits_tx1)

print(f"Analizando {name} con sincronización por fase...")

for k, rot in enumerate([1, 1j, -1, -1j]):
    fase_label = k * 90

    # Aplicamos la rotación a toda la señal antes de sincronizar
    rx_rot = data * rot
    #print("data dtype:", data.dtype)
    # Sincronizamos buscando el pico en la parte REAL para esta rotación
    tx_s, rx_s, delay, corr_i, corr_q = sync_by_components1(tx_ref, rx_rot)

    #print(f'tx_s:',tx_s[:5], f'rx_s:', rx_s[:5])

    # Demodulamos y calculamos BER
    b_ref = demodular_qpsk(tx_s)
    b_rx = demodular_qpsk(rx_s)

    n = min(len(b_ref), len(b_rx))
    ber = np.mean(b_ref[:n] != b_rx[:n])

    # Guardamos los datos para comparar
    resultados.append({
        'rot': fase_label,
        'ber': ber,
        'delay': delay,
        'sig': rx_s,
        'corr_plot': corr_i + corr_q
    })

    print(f" > Fase {fase_label}°: BER = {ber:.6f} | Pico Real detectado en lag {delay}")

# --- ELECCIÓN DEL MEJOR RESULTADO ---
mejor = min(resultados, key=lambda x: x['ber'])

# Visualización de la correlación que dio el mejor BER
plt.figure(figsize=(10, 4))
plt.plot(mejor['corr_plot'])
plt.title(f"Mejor Correlación Real (Fase {mejor['rot']}°)")
plt.grid(True)
plt.show()

# Constelación final
plot_constellation(mejor['sig'], title=f"Resultado: {mejor['rot']}° | BER: {mejor['ber']:.5f}")

name = "coax_1mbps_650mhz_snrXdB.bin"
data = np.fromfile(name, dtype=np.complex64)
tx_ref = bits_to_qpsk(bits_tx1)

def sync_by_components(tx_ideal, rx_long):
    """
    Sincroniza correlacionando I y Q de forma independiente y sumando sus contribuciones.
    """
    eps = 1e-9  # <-- EPSILON para evitar colapso numérico

    # 1. Normalización ROBUSTA
    tx_i = (tx_ideal.real - np.mean(tx_ideal.real)) / (np.std(tx_ideal.real) + eps)
    tx_q = (tx_ideal.imag - np.mean(tx_ideal.imag)) / (np.std(tx_ideal.imag) + eps)

    rx_i = (rx_long.real - np.mean(rx_long.real)) / (np.std(rx_long.real) + eps)
    rx_q = (rx_long.imag - np.mean(rx_long.imag)) / (np.std(rx_long.imag) + eps)

    # 2. Correlaciones cruzadas independientes
    corr_ii = np.correlate(rx_i, tx_i, mode="full")
    corr_qq = np.correlate(rx_q, tx_q, mode="full")

    # 3. Suma de correlaciones
    total_corr = corr_ii + corr_qq

    lags = np.arange(-len(tx_ideal) + 1, len(rx_long))
    delay = lags[np.argmax(total_corr)]

    # 4. Recorte (igual que antes)
    if delay < 0:
        rx_sync = rx_long[0 : len(tx_ideal) + delay]
        tx_sync = tx_ideal[-delay : -delay + len(rx_sync)]
    else:
        rx_sync = rx_long[delay : delay + len(tx_ideal)]
        tx_sync = tx_ideal[:len(rx_sync)]

    return tx_sync, rx_sync, delay, corr_ii, corr_qq
# --- PARÁMETROS ---
#name = datos1.files[35]
#name = "rof_2km_1mbps_650mhz_osnr35p72dB_snr8p57dB"
#name = "rof_2km_1mbps_650mhz_osnr35p72dB_snr8p83dB"
#name = "rof_2km_1mbps_650mhz_osnr35p72dB_snr9p09dB"
#name = "rof_2km_1mbps_650mhz_osnr35p72dB_snr9p50dB"
#name = "rof_2km_1mbps_650mhz_osnr35p72dB_snr9p61dB"
print(name)
#print(f'data:', data[:5])
tx_ref = bits_to_qpsk(bits_tx1)
resultados = []

print(f"Analizando {name} con sincronización por fase...")

for k, rot in enumerate([1, 1j, -1, -1j]):
    fase_label = k * 90

    # Aplicamos la rotación a toda la señal antes de sincronizar
    rx_rot = data * rot
    #print("data dtype:", data.dtype)
    # Sincronizamos buscando el pico en la parte REAL para esta rotación
    tx_s, rx_s, delay, corr_i, corr_q = sync_by_components1(tx_ref, rx_rot)

    #print(f'tx_s:',tx_s[:5], f'rx_s:', rx_s[:5])

    # Demodulamos y calculamos BER
    b_ref = demodular_qpsk(tx_s)
    b_rx = demodular_qpsk(rx_s)

    n = min(len(b_ref), len(b_rx))
    ber = np.mean(b_ref[:n] != b_rx[:n])

    # Guardamos los datos para comparar
    resultados.append({
        'rot': fase_label,
        'ber': ber,
        'delay': delay,
        'sig': rx_s,
        'corr_plot': corr_i + corr_q
    })

    print(f" > Fase {fase_label}°: BER = {ber:.6f} | Pico Real detectado en lag {delay}")

# --- ELECCIÓN DEL MEJOR RESULTADO ---
mejor = min(resultados, key=lambda x: x['ber'])

# Visualización de la correlación que dio el mejor BER
plt.figure(figsize=(10, 4))
plt.plot(mejor['corr_plot'])
plt.title(f"Mejor Correlación Real (Fase {mejor['rot']}°)")
plt.grid(True)
plt.show()

# Constelación final
plot_constellation(mejor['sig'], title=f"Resultado: {mejor['rot']}° | BER: {mejor['ber']:.5f}")

#CÓDIGO FINAL
tx_ref = bits_to_qpsk(bits_tx1)

resultados_globales = []

for idx, name in enumerate(datos2.files):
    data = datos2[name]
    resultados = []

    print(f"\nAnalizando archivo {idx} → {name} con sincronización por fase...")

    for k, rot in enumerate([1, 1j, -1, -1j]):
        fase_label = k * 90

        # Rotación de fase
        rx_rot = data * rot

        # Sincronización
        tx_s, rx_s, delay, corr_i, corr_q = sync_by_components1(
            tx_ref, rx_rot
        )

        # Demodulación
        b_ref = demodular_qpsk(tx_s)
        b_rx  = demodular_qpsk(rx_s)

        n = min(len(b_ref), len(b_rx))
        ber = np.mean(b_ref[:n] != b_rx[:n])

        resultados.append({
            'archivo': name,
            'rot': fase_label,
            'ber': ber,
            'delay': delay,
            'sig': rx_s,
            'corr_plot': corr_i + corr_q
        })

        print(f"  > Fase {fase_label}°: BER = {ber:.6e} | Delay = {delay}")

    # --- Mejor resultado por archivo ---
    mejor = min(resultados, key=lambda x: x['ber'])
    resultados_globales.append(mejor)

    print(
        f" ✔ Mejor fase para {name}: "
        f"{mejor['rot']}° | BER = {mejor['ber']:.6e}"
    )

print(resultados_globales)

ber_por_osnr = defaultdict(list)

for r in resultados_globales:
    osnr = extraer_osnr(r['archivo'])
    if osnr is not None:
        ber_por_osnr[osnr].append(float(r['ber']))

osnr_vals = np.array(sorted(ber_por_osnr.keys()))
ber_mean  = np.array([np.mean(ber_por_osnr[o]) for o in osnr_vals])
ber_std   = np.array([np.std(ber_por_osnr[o])  for o in osnr_vals])  # opcional


plt.figure(figsize=(7, 5))
plt.semilogy(osnr_vals, ber_mean, 'o-', linewidth=2, label='BER promedio')

plt.xlabel("OSNR [dB]")
plt.ylabel("BER")
plt.title("BER vs OSNR (promediado)")

plt.grid(True, which='both', linestyle='--', alpha=0.6)
plt.legend()
plt.tight_layout()
plt.show()

MAX_SYMBOLS = 20_000
segmento_rx = data[:MAX_SYMBOLS]
autocorr = np.correlate(segmento_rx, np.conj(segmento_rx), mode='full')
mag_autocorr = np.abs(autocorr)

plt.figure(figsize=(12, 4))
plt.plot(mag_autocorr)
plt.title("Autocorrelación de la Señal Recibida")
plt.show()